version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.11

    steps:
      - checkout
      - run:
          name: set env
          command: echo $ENV | base64 --decode > .env
      - run:
          name: set firebase cons
          command: echo $FIREBASE_CONF | base64 --decode > ./src/firebse/config.js

      - run:
          name: update-npm
          command: sudo npm install -g npm
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build-npm
          command: npm run build
      
      - deploy:
          name: deploy-firebase
          command: firebase deploy --project "$FIREBASE_PJ" --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build